### PR TITLE
WIP: Common code refactoring

### PR DESCRIPTION
**Pull request by tpetrina**
# DO NOT MERGE THIS YET

This pull request will be open until I merge in all code changes. Until that time, use this pull request to check what and how it is being done.

In case you have suggestions, feel free to write them here.

NuGet package changes:

 - Upgraded `FFmpeg.AutoGen` to 3.4.0.1

TODO:
- [x] Extract Core namespace
- [x] Extract Commands, Decoding and Rendering namespaces
- [x] Move all logic from `MediaElement` to `MediaElementCore`
- [x] Add initial macOS implementation to show it works
- [x] Add simple video renderer for macOS

Tracking issue #104.

### CODE REVIEW

**Comment by tpetrina** [comment]
Waiting for https://github.com/Ruslan-B/FFmpeg.AutoGen/pull/80 before this can be finished.

**Comment by tpetrina** [comment]
I need to add some build instructions and then I think this initial refactoring is done.

**Comment by mariodivece** [comment]
Let me know when I can do the merge.

**Comment by tpetrina** [comment]
Just let me figure out why VS2017 won't build it and VS for Mac builds just fine.

**Comment by tpetrina** [comment]
Alright, it builds properly and docs for macOS sample player are in there. I think you can review the changes now and see if everything is ok.

Note that we can now start on proper player implementation and also implementing sound for macOS. It would be fun to see if this player can be ported to Android, iOS and UWP as well.

**Comment by mariodivece** [comment]
Ok, I am merging for now and will review when I have more spare time. Thanks so much @tpetrina The Platform independent implementations look awesome!

**Comment by mariodivece** [comment]
@teptrina what are you using to open the macOS project with Visual Studio -- it tells me the project type is unsupported.

**Comment by tpetrina** [comment]
Either Visual Studio for Mac or VS2017 with Xamarin support installed. It is a mono project.

**Pull request merged**
