### PR TITLE
Master

### PR DESCRIPTION
**Pull request by EsMoDavid**

### CODE REVIEW

**Comment by mariodivece** [comment]
@EsMoDavid could you please explain what problem exactly does this change solve?

**Comment by EsMoDavid** [comment]
> @EsMoDavid could you please explain what problem exactly does this change solve?

In my case, url = "https://internal-dev:4443/files/portal/g/30013/cust/Red%20Dead%20Redemption%202%20Launch%20Trailer.mp4/V1/Red%20Dead%20Redemption%202%20Launch%20Trailer.mp4"

When I create Uri object(new Uri(url)), %20 will be replaced to space, so the Uri.ToString() is 
https://internal-dev:4443/files/portal/g/30013/cust/Red Dead Redemption 2 Launch Trailer.mp4/V1/Red Dead Redemption 2 Launch Trailer.mp4

At last method "ffmpeg.avformat_open_input" will be failed to open the url
image

**Comment by mariodivece** [comment]
Could you try with the latest commit and let me know?

**Comment by EsMoDavid** [comment]
> Could you try with the latest commit and let me know?

awesome! It's ok for both space and %20

**Pull request merged**
